export const BRAND_CONFIG = {
  restaurantName: "THE XINGS KITCHEN",
  restaurantShortName: "THE XINGS KITCHEN",
  adminTitle: "THE XINGS KITCHEN ADMIN CONTROL CENTER",
  adminHeader: "THE XINGS KITCHEN ADMIN",
  adminSubheader: "ADMINISTRATION OVERVIEW",
  posTitle: "THE XINGS KITCHEN POS",
  posSubtitle: "Restaurant POS & Operations",
  receiptName: "THE XINGS KITCHEN",
  receiptTagline: "Contemporary Asian & Indo-Chinese Dining",
  kotHeader: "THE XINGS KITCHEN",
  kotTitle: "KITCHEN ORDER TICKET",
  cuisine: "Contemporary Asian & Indo-Chinese",
  established: "ESTD 2018",
  legalName: "THE XINGS KITCHEN PRIVATE LIMITED",
  city: "Nagpur",
  state: "Maharashtra",
  tagline: "Contemporary Asian & Indo-Chinese Kitchen",
  subtagline: "Authentic Wok Delights, Dim Sums, Handcrafted Noodles & Signature Fusion Specials",
  defaultAddress: "Shop 4 & 5, Galaxy Tower, Central Avenue, Commercial District",
  defaultPhone: "+91 98765 43210",
  defaultEmail: "orders@thexingskitchen.com",
  defaultWebsite: "thexingskitchen.com",
  defaultGstin: "27AAACX9876F1Z2",
  defaultFssai: "11524056000189",
  defaultCurrency: "₹",
  defaultHours: "Mon - Sun: 11:00 AM - 11:00 PM",
  colors: {
    dark: "#0D0D0D",
    charcoal: "#141414",
    surface: "#1C1917",
    cream: "#FBF9F5",
    warmWhite: "#FFFFFF",
    gold: "#D4AF37",
    goldHover: "#B8860B",
    goldMuted: "#AA7C11",
  }
} as const;

export type BrandConfig = typeof BRAND_CONFIG;
