import { MenuItem, Category, Review } from "./types";

export const categories: Category[] = [
  {
    id: "idli",
    name: "Idli Varieties",
    icon: "🥟",
    description: "Nagpur's softest fluffy steamed idlis starting at just ₹10"
  },
  {
    id: "dosa",
    name: "Dosas",
    icon: "🥞",
    description: "Crispy South Indian crepes with delicious fillings"
  },
  {
    id: "breakfast",
    name: "Traditional Breakfast",
    icon: "🍛",
    description: "Delicious traditional South Indian morning favorites"
  },
  {
    id: "uttapam",
    name: "Uttapam",
    icon: "🍕",
    description: "Thick South Indian pancakes with savory toppings"
  },
  {
    id: "beverages",
    name: "Beverages",
    icon: "☕",
    description: "Chilled drinks and traditional filter coffee"
  }
];

export const menuItems: MenuItem[] = [
  {
    id: "i1",
    itemCode: "IJ-ID-01",
    category: "idli",
    name: "Regular Idli",
    description: "Soft, fluffy, and steaming hot traditional idli, served with aromatic fresh sambar and coconut chutney.",
    price: 10,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    ratingCount: 340,
    isBestseller: true,
    isChefSpecial: false,
    spiciness: 0,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i2",
    itemCode: "IJ-ID-02",
    category: "idli",
    name: "Ghee Thatte Idli",
    description: "Large, plate-sized, pillowy soft Thatte Idli smeared with pure clarified butter (ghee) and spicy podi.",
    price: 40,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    ratingCount: 185,
    isBestseller: true,
    isChefSpecial: true,
    spiciness: 1,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i3",
    itemCode: "IJ-ID-03",
    category: "idli",
    name: "Mini Podi Idli",
    description: "Bite-sized button idlis tossed in pure ghee and spicy, flavorful gunpowder (podi) spice mix.",
    price: 35,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    ratingCount: 120,
    isBestseller: false,
    isChefSpecial: false,
    spiciness: 1,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i4",
    itemCode: "IJ-DOS-01",
    category: "dosa",
    name: "Plain Dosa",
    description: "Thin, crispy golden crepe made from perfectly fermented rice-lentil batter, served with fresh sambar and coconut chutney.",
    price: 40,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=600",
    rating: 4.5,
    ratingCount: 95,
    isBestseller: false,
    isChefSpecial: false,
    spiciness: 0,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i5",
    itemCode: "IJ-DOS-02",
    category: "dosa",
    name: "Mysore Masala Dosa",
    description: "Crispy crepe layered with spicy red garlic-chili chutney, stuffed with tempered potato-onion masala.",
    price: 60,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    ratingCount: 215,
    isBestseller: true,
    isChefSpecial: true,
    spiciness: 2,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i6",
    itemCode: "IJ-DOS-03",
    category: "dosa",
    name: "Cheese Dosa",
    description: "Crispy wafer-thin golden crepe loaded with melted, rich, and creamy grated mozzarella cheese.",
    price: 70,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=600",
    rating: 4.6,
    ratingCount: 142,
    isBestseller: false,
    isChefSpecial: false,
    spiciness: 0,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i7",
    itemCode: "IJ-BRK-01",
    category: "breakfast",
    name: "Sambar Wada",
    description: "Crisp, golden-brown deep-fried lentil donuts, soaked in hot, tangy, and rich traditional sambar.",
    price: 30,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    ratingCount: 260,
    isBestseller: true,
    isChefSpecial: false,
    spiciness: 1,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i8",
    itemCode: "IJ-BRK-02",
    category: "breakfast",
    name: "Upma",
    description: "Warm, savory semolina porridge roasted with mustard seeds, curry leaves, ginger, green chilies, and crunchy cashews.",
    price: 25,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    rating: 4.4,
    ratingCount: 110,
    isBestseller: false,
    isChefSpecial: false,
    spiciness: 0,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i9",
    itemCode: "IJ-UTP-01",
    category: "uttapam",
    name: "Onion Uttapam",
    description: "Thick South Indian rice pancake cooked with finely chopped, caramelized sweet onions, fresh coriander, and green chilies.",
    price: 50,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    ratingCount: 135,
    isBestseller: false,
    isChefSpecial: false,
    spiciness: 1,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i10",
    itemCode: "IJ-UTP-02",
    category: "uttapam",
    name: "Tomato Uttapam",
    description: "Thick, soft rice pancake topped with juicy, tangily roasted tomato slices, fresh green chilies, and coriander.",
    price: 50,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=600",
    rating: 4.5,
    ratingCount: 98,
    isBestseller: false,
    isChefSpecial: false,
    spiciness: 1,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i11",
    itemCode: "IJ-BEV-01",
    category: "beverages",
    name: "Authentic South Indian Filter Coffee",
    description: "Strong, frothy chicory-blended coffee hand-pulled with hot milk, brewed in a traditional metal filter.",
    price: 20,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    ratingCount: 420,
    isBestseller: true,
    isChefSpecial: true,
    spiciness: 0,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i12",
    itemCode: "IJ-DOS-04",
    category: "dosa",
    name: "Paneer Dosa",
    description: "Crispy golden dosa generously filled with fresh spiced malai paneer and green herbs.",
    price: 80,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    ratingCount: 160,
    isBestseller: true,
    isChefSpecial: true,
    spiciness: 1,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i13",
    itemCode: "IJ-BRK-03",
    category: "breakfast",
    name: "Sambar Vada Dip",
    description: "Crisp urad dal vada submerged in a large bowl of bubbling hot lentil vegetable sambar.",
    price: 35,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    ratingCount: 115,
    isBestseller: false,
    isChefSpecial: false,
    spiciness: 1,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i14",
    itemCode: "IJ-EXT-01",
    category: "breakfast",
    name: "Fresh Coconut Chutney",
    description: "Freshly grated coconut ground with roasted gram, green chillies, ginger, and tempered with mustard seeds.",
    price: 15,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    ratingCount: 210,
    isBestseller: false,
    isChefSpecial: false,
    spiciness: 1,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i15",
    itemCode: "IJ-EXT-02",
    category: "breakfast",
    name: "Spicy Tomato Chutney",
    description: "Tangy roasted tomato and onion relish tempered with red chillies, mustard, and curry leaves.",
    price: 15,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=600",
    rating: 4.6,
    ratingCount: 140,
    isBestseller: false,
    isChefSpecial: false,
    spiciness: 2,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i16",
    itemCode: "IJ-BRK-04",
    category: "breakfast",
    name: "Kanda Poha",
    description: "Nagpur special flattened rice tempered with onions, turmeric, green chillies, mustard seeds, and fresh lemon.",
    price: 30,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    ratingCount: 195,
    isBestseller: true,
    isChefSpecial: false,
    spiciness: 1,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i17",
    itemCode: "IJ-CUR-01",
    category: "breakfast",
    name: "Paneer Masala",
    description: "Succulent malai paneer cubes simmered in a spiced tomato, onion, and rich cashew-cream gravy.",
    price: 120,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    ratingCount: 280,
    isBestseller: true,
    isChefSpecial: true,
    spiciness: 2,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i18",
    itemCode: "IJ-BEV-02",
    category: "beverages",
    name: "Masala Cutting Chai",
    description: "Invigorating hot tea brewed with Assam CTC tea leaves, fresh crushed ginger, and aromatic spices.",
    price: 15,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    ratingCount: 310,
    isBestseller: true,
    isChefSpecial: false,
    spiciness: 0,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i19",
    itemCode: "IJ-BEV-03",
    category: "beverages",
    name: "Fresh Lemon Water",
    description: "Chilled refreshment made with freshly squeezed Nagpur lemons, sugar, and a pinch of rock salt.",
    price: 20,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&q=80&w=600",
    rating: 4.6,
    ratingCount: 105,
    isBestseller: false,
    isChefSpecial: false,
    spiciness: 0,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  },
  {
    id: "i20",
    itemCode: "IJ-BRK-05",
    category: "breakfast",
    name: "Curd Rice",
    description: "Cooling seasoned rice mixed with fresh creamy curd, tempered with mustard seeds, curry leaves, and ginger.",
    price: 60,
    isVeg: true,
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    ratingCount: 140,
    isBestseller: false,
    isChefSpecial: false,
    spiciness: 0,
    gstPercent: 5,
    hsnCode: "21069099",
    available: true
  }
];

export const reviews: Review[] = [
  {
    id: "r1",
    name: "Rohan Deshmukh",
    rating: 5,
    date: "2026-07-14",
    comment: "The softest idlis I've ever had in Nagpur! Absolutely pocket-friendly and hygienic. The filter coffee is outstanding.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100"
  },
  {
    id: "r2",
    name: "Prachi Sharma",
    rating: 5,
    date: "2026-07-15",
    comment: "Ghee Thatte Idli is a must-try here! Incredible value for money, authentic taste, and fast service.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100"
  }
];
